"""
This type stub file was generated by pyright.
"""

__all__ = ['CacheHandler', 'CacheFileHandler', 'DjangoSessionCacheHandler', 'MemoryCacheHandler']
logger = ...
class CacheHandler:
    """
    An abstraction layer for handling the caching and retrieval of
    authorization tokens.

    Custom extensions of this class must implement get_cached_token
    and save_token_to_cache methods with the same input and output
    structure as the CacheHandler class.
    """
    def get_cached_token(self):
        """
        Get and return a token_info dictionary object.
        """
        ...
    
    def save_token_to_cache(self, token_info):
        """
        Save a token_info dictionary object to the cache and return None.
        """
        ...
    


class CacheFileHandler(CacheHandler):
    """
    Handles reading and writing cached Spotify authorization tokens
    as json files on disk.
    """
    def __init__(self, cache_path=..., username=...) -> None:
        """
        Parameters:
             * cache_path: May be supplied, will otherwise be generated
                           (takes precedence over `username`)
             * username: May be supplied or set as environment variable
                         (will set `cache_path` to `.cache-{username}`)
        """
        ...
    
    def get_cached_token(self): # -> Any | None:
        ...
    
    def save_token_to_cache(self, token_info): # -> None:
        ...
    


class MemoryCacheHandler(CacheHandler):
    """
    A cache handler that simply stores the token info in memory as an
    instance attribute of this class. The token info will be lost when this
    instance is freed.
    """
    def __init__(self, token_info=...) -> None:
        """
        Parameters:
            * token_info: The token info to store in memory. Can be None.
        """
        ...
    
    def get_cached_token(self):
        ...
    
    def save_token_to_cache(self, token_info): # -> None:
        ...
    


class DjangoSessionCacheHandler(CacheHandler):
    """
    A cache handler that stores the token info in the session framework
    provided by Django.

    Read more at https://docs.djangoproject.com/en/3.2/topics/http/sessions/
    """
    def __init__(self, request) -> None:
        """
        Parameters:
            * request: HttpRequest object provided by Django for every
            incoming request
        """
        ...
    
    def get_cached_token(self): # -> None:
        ...
    
    def save_token_to_cache(self, token_info): # -> None:
        ...
    


