"""
This type stub file was generated by pyright.
"""

class SpotifyException(Exception):
    def __init__(self, http_status, code, msg, reason=..., headers=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


